#!/usr/bin/env bash
# filter_domain_issues.sh
#
# Domain 规则扫描结果过滤脚本（白名单/已知误报自动剔除）。
#
# 说明：
#   - 当 Domain 规则识别到一条疑似问题后，将 (file_path, domain) 传入本脚本，
#     若命中以下任一白名单则视为误报，应从最终报告中过滤掉：
#       1) file_path 匹配 DOMAIN_FILTER_FILE_PATH_PATTERNS 任一模式；
#       2) domain    匹配 DOMAIN_FILTER_DOMAIN_PATTERNS     任一模式。
#   - 匹配采用 bash `[[ $value == $pattern ]]` 的内置 glob 风格，`*` 可匹配
#     包括 `/` 在内的任意字符串。模式与 SKILL 规则文档（Domain.md）保持一致。
#
# 路径解析约定：
#   下文示例中的 `scripts/filter_domain_issues.sh` 是相对本 Skill 根目录的路径。
#   $SKILL_ROOT 由调用方（Agent / 扫描器）在运行时解析为本 Skill 的实际绝对路径，
#   不要把开发仓库内的相对路径（如 plugins/.../code-compliance-checker/）硬编码进调用脚本。
#
# 使用方式：
#   方式 A（推荐，作为库 source 后调用函数）：
#     source "$SKILL_ROOT/scripts/filter_domain_issues.sh"
#     if should_filter_domain_issue "$file_path" "$domain"; then
#       continue   # 命中白名单，丢弃本条问题
#     fi
#
#   方式 B（独立 CLI，使用 TAB 分隔的 stdin → stdout 流式过滤）：
#     printf '%s\t%s\n' "$file_path" "$domain" | \
#       bash "$SKILL_ROOT/scripts/filter_domain_issues.sh"
#     # 命中白名单的行被丢弃；其他原样输出到 stdout（可保留额外尾列）。
#
# 退出码（函数）：
#   0 → 命中白名单，应过滤（drop）
#   1 → 未命中，保留（keep）

# ---------------------------------------------------------------------------
# 白名单 1：问题所在文件路径（命中则过滤）
# ---------------------------------------------------------------------------
DOMAIN_FILTER_FILE_PATH_PATTERNS=(
  "*.md"
  "*.sh"
  "*.d.ts"
  "*gradle*"
  "*.pbxproj"
  "*.podspec"
  "*.doxyfile"
  "*.makefile"
  "*.markdown"
  "*.changelog"
  "*.configure"
  "*/zk_rules/*"
  "*/debug/*"
  "*/debugger/*"
  "*/example/*"
  "*/examples/*"
  "*/test/*"
  "*/tests/*"
  "*/testing/*"
  "*/sample/*"
  "*/samples/*"
  "*/demo/*"
  "*/demos/*"
  "*.log"
  "*.make"
  "*.cmake"
  "*NOTICE"
  "*cdn.js"
  "*Gemfile"
  "*Podfile"
  "*license"
  "*/ttquic/*"
  "*pods.json"
  "*unittest*"
  "*NOTICE.txt"
  "*README.txt"
  "*/audiosdk/*"
  "*/ttffmpeg/*"
  "*DEPENDENCIES"
  "*.lock"
  "*podspec.json"
  "*/quiche/quic/*"
  "*zstd-reduce*"
  "*Dependency.kt"
  "*/rtmp_quic/libquic/*"
  "*AndroidManifest.xml"
  "*/mammon_engine/thirdparty/*"
  "*/nail-slam/ThirdParty/Catch2/*"
  "*/amazing_engine/amazing_engine/*"
  "*/audio_effect/thirdparty/eigen/*"
  "*/audio_effect/thirdparty/google/*"
  "*/TikTok/main/src/i18n/assets/i18/*"
  "*/ttvideoeditor/ttvebase/src/thirdparty/ffmpeg/*"
  "*/ss/android/ugc/aweme/net/config/DMTNetConfig.java"
  "*/eden.monorepo.json"
  "*/eden.mono.pipeline.json"
  "*/pnpm-lock.yaml"
)

# ---------------------------------------------------------------------------
# 白名单 2：检出的问题域名（命中则过滤）
# ---------------------------------------------------------------------------
DOMAIN_FILTER_DOMAIN_PATTERNS=(
  "*cloud-i18n.sinf.net"
  "*cloud.sinf.net"
  "*metrics-us.byted.org"
  "*larkoffice.com"
  "*-boe.bytedance.net"
  "*-sglark.bytdance.net"
  "*-va.bytedance.net"
  "*4code.byted.org"
  "*8df9x59b.fn.bytedance.net"
  "*acp-cn.bytedance.net"
  "*acp-sy.bytedance.net"
  "*acp-vac.bytedance.net"
  "*acp-wj.bytedance.net"
  "*aegis.bytedance.net"
  "*aliyun-sin-hub.byted.org"
  "*aliyun-va-hub.byted.org"
  "*amazon.com"
  "*amazonaws.com"
  "*anywhere.bytedance.net"
  "*apache.org"
  "*api.amemv.com"
  "*apple.com"
  "*approval-tra.bytedance.net"
  "*appspot.com"
  "*appveyor.com"
  "*apt.byted.org"
  "*avisynth.nl"
  "*awsgrafana.byted.org"
  "*baisong.com"
  "*bdcdn-cache-app-api-mva.bytedance.net"
  "*bdcdn-grafana-hl.bytedance.net"
  "*bdcdn-grafana-lq.bytedance.net"
  "*bhub.byted.org"
  "*blogs.msdn.com"
  "*blogspot.com"
  "*bnpm.bytedance.net"
  "*boe-ee.byted.org"
  "*boe-grafana-appsec.byted.org"
  "*boe.bytedance.net"
  "*boei18n-grafana-appsec.byted.org"
  "*boei18n2-grafana-appsec.byted.org"
  "*boelq-grafana-appsec.byted.org"
  "*bpm-tx.bytedance.net"
  "*bpm.bytedance.net"
  "*byteapi.byted.org"
  "*bytebox.bytedance.net"
  "*bytediff.bytedance.net"
  "*bytedpypi.byted.org"
  "*bytedtrace.byted.org"
  "*bytees-lark-qm-coral.bytedance.net"
  "*bytekm.bytedance.net"
  "*bytelemon.com"
  "*byteoversea.com"
  "*byteoversea.net"
  "*bytepaas-proxy.byted.org"
  "*bytetree.byted.org"
  "*caojia.com"
  "*cdaas.byted.org"
  "*cdn.jsdelivr.net"
  "*cloud-boe.bytedance.net"
  "*cloud-iam-tx.bytedance.net"
  "*cloud-openapi-tx.bytedance.net"
  "*cloud-page-tx.bytedance.net"
  "*cloud-tx.bytedance.net"
  "*cloud.bytedance.net"
  "*cloudapi.bytedance.net"
  "*code.byted.org"
  "*codebase.byted.org"
  "*contract-test.bytedance.net"
  "*coveralls.io"
  "*crl.globalsign.net"
  "*data-va.bytedance.net"
  "*data.bytedance.net"
  "*datahub.service.datahub.byted.org"
  "*datapalace.bytedance.net"
  "*datapalaceva.bytedance.net"
  "*dataplatform.jupyter.cn"
  "*dave.cheney.net"
  "*developer.mozilla.org"
  "*devops.bytedance.net"
  "*dg-bos.bytedance.net"
  "*dg.bytedance.net"
  "*diancha-os.bytedance.net"
  "*doc.bytedance.net"
  "*docker.com"
  "*docker.io"
  "*dockerhub.byted.org"
  "*docs.bytedance.net"
  "*docs.nvidia.com"
  "*dpsg-grafana-lq.byted.org"
  "*ea-common-1.bytedance.net"
  "*ea-sre.bytedance.net"
  "*ea-zk.bytedance.net"
  "*eden.bytedance.net"
  "*ee.byted.org"
  "*ei.byted.org"
  "*elasticbeanstalk.com"
  "*everphoto.cn"
  "*ewd.byted.org"
  "*example.com"
  "*example.net"
  "*f-p-pci.bytedance.net"
  "*f-p.bytedance.net"
  "*fastly.net"
  "*feishu.cn"
  "*fin.bytedance.net"
  "*fr.byted.org"
  "*freebsd.org"
  "*fsopen.bytedance.net"
  "*gaea-hub.byted.org"
  "*galaxy-api-tx.bytedance.net"
  "*galaxy-api.byted.org"
  "*galaxy-api.bytedance.net"
  "*galaxy-cmdb.bytedance.net"
  "*galaxy-portal-tx.bytedance.net"
  "*galaxy-portal.bytedance.net"
  "*gcp.bytedance.net"
  "*git.byted.org"
  "*github.com"
  "*github.io"
  "*githubusercontent.com"
  "*global-whale.bytedance.net"
  "*globalsign.com"
  "*gnu.org"
  "*go-mod-proxy.byted.org"
  "*goofy.byted.org"
  "*google.com"
  "*googleapis.com"
  "*googlesource.com"
  "*goproxy.byted.org"
  "*goproxy.cn"
  "*goproxy.io"
  "*grafana-bk-hl.bytedance.net"
  "*grafana-bk-lq.bytedance.net"
  "*grafana-bk.bytedance.net"
  "*grafana-boe.byted.org"
  "*grafana-boe.xfl.net"
  "*grafana-boeinf.byted.org"
  "*grafana-gcp.byted.org"
  "*grafana-hl.byted.org"
  "*grafana-i18n.byted.org"
  "*grafana-lf.byted.org"
  "*grafana-limited.byted.org"
  "*grafana-lq.byted.org"
  "*grafana-oci.byted.org"
  "*grafana-row.byted.org"
  "*grafana-testbed-lq.bytedance.net"
  "*grafana-testbed.bytedance.net"
  "*grafana-texas.byted.org"
  "*grafana-ttp-us-limit.byted.org"
  "*grafana-ttp-us.byted.org"
  "*grafana-tx.byted.org"
  "*grafana-us.byted.org"
  "*grafana.byted.org"
  "*grafana.bytedance.net"
  "*grafana.teleport.row-dev.secinfra.byted.org"
  "*gtf-android.bytedance.net"
  "*hjqd-grafana-appsec.byted.org"
  "*hl-grafana-appsec.byted.org"
  "*holmes-qd.bytedance.net"
  "*hub.byted.org"
  "*i-admin.bytedance.net"
  "*i-b-feedback.bytedance.net"
  "*i-cia.bytedance.net"
  "*i-cm.bytedance.net"
  "*i-content.bytedance.net"
  "*i-ee-external.bytedance.net"
  "*i-ee.byted.org"
  "*i-ei.byted.org"
  "*i-hornbill.bytedance.net"
  "*i18n.bytedance.net"
  "*i18ntableau.bytedance.net"
  "*iam.bytedance.net"
  "*ibytedtos.com"
  "*images.unsplash.com"
  "*inf.bytedance.net"
  "*infosec-lab-grafana-appsec.byted.org"
  "*install.byted.org"
  "*it-grafana-hl.bytedance.net"
  "*it-grafana-lf.bytedance.net"
  "*java.com"
  "*java.net"
  "*jetbrains.com"
  "*jimu-bos.bytedance.net"
  "*jimu.bytedance.net"
  "*jira.bytedance.com"
  "*jiyunhudong.com"
  "*jn75o3iq.sg-fn.bytedance.net"
  "*json.org"
  "*kernel.org"
  "*kms-row.bytedance.net"
  "*krb5auth.byted.org"
  "*krb5auth1.byted.org"
  "*krb5auth2.byted.org"
  "*krb5auth3.byted.org"
  "*lab.bytedance.net"
  "*lark-open.bytedance.net"
  "*legal-1.bytedance.net"
  "*legal-cn.bytedance.net"
  "*legal-pre.bytedance.net"
  "*legal.bytedance.net"
  "*lf-grafana-appsec.byted.org"
  "*lighthouse.bytedance.net"
  "*loadtest-useast2a-grafana-appsec.byted.org"
  "*lq-grafana-appsec.byted.org"
  "*luban-source.byted.org"
  "*maliva-grafana-appsec.byted.org"
  "*maliva-sgreplica-kaniapis.byted.org"
  "*maliva.bytedance.net"
  "*master.bytedance.net"
  "*maven.byted.org"
  "*md-er.bytedance.net"
  "*md-test.bytedance.net"
  "*md.bytedance.net"
  "*meego.bytedance.net"
  "*metrics.byted.org"
  "*microsoft.com"
  "*mirrors.byted.org"
  "*mmm.bytedance.net"
  "*mock.bytedance.net"
  "*mon.isnssdk.com"
  "*mongodb.com"
  "*mongodb.org"
  "*mozilla.org"
  "*mpaas-debug-hl.bytedance.net"
  "*mpaas-debug-lf.bytedance.net"
  "*mpaas-debug-lq.bytedance.net"
  "*mpaas-debug.bytedance.net"
  "*mpaas.bytedance.net"
  "*mpsso-bos.bytedance.net"
  "*mpsso-os.bytedance.net"
  "*mr-history-sgeeea.bytedance.net"
  "*ms.byted.org"
  "*mt-qrec-trends-api.bytedance.net"
  "*muscdn.com"
  "*musetool.bytedance.net"
  "*mva-appbeta.bytedance.net"
  "*mva-v-lambda.bytedance.net"
  "*mvaali-admin.bytedance.net"
  "*n2w1i9oo.us-east-fn.bytedance.net"
  "*node.byted.org"
  "*nodejs.bytedance.net"
  "*ns.adobe.com"
  "*nsq.byted.org"
  "*oa-pre.bytedance.net"
  "*oa-test.bytedance.net"
  "*oa.bytedance.com"
  "*oa.bytedance.net"
  "*oncall-tx.bytedance.net"
  "*open.byted.org"
  "*open.feishu-boe.cn"
  "*opensource.org"
  "*opstats.bytedance.net"
  "*oracle.com"
  "*org.apache.hadoop.net"
  "*overpass.bytedance.net"
  "*oversea.bytedance.net"
  "*p16-ad-gcp.tiktokcdn-in.com"
  "*p19-sign.tiktokcdn-us.com"
  "*paas-gw-boe.byted.org"
  "*paas-gw-boe.xfl.net"
  "*paas-gw-boei18n.byted.org"
  "*paas-gw-boeinf.byted.org"
  "*paas-gw-hl.byted.org"
  "*paas-gw-i18n-useast2a.byted.org"
  "*paas-gw-i18n.byted.org"
  "*paas-gw-lf.byted.org"
  "*paas-gw-lq.byted.org"
  "*paas-gw-sandbox-boe.byted.org"
  "*paas-gw-sandbox.byted.org"
  "*paas-gw-sdqd.byted.org"
  "*paas-gw-tx.byted.org"
  "*paas-gw-us.byted.org"
  "*paas-gw.byted.org"
  "*paas-gw.xfl.net"
  "*paas-tao-lq.bytedance.net"
  "*paas-tao.bytedance.net"
  "*paas.byted.org"
  "*pangleglobal.com"
  "*pangu.bytedance.net"
  "*pearl.bytedance.net"
  "*people.bytedance.net"
  "*pigeon.byted.org"
  "*pipo-admin.bytedance.net"
  "*pipo-devbox.bytedance.net"
  "*pipo-fe-devbox.bytedance.net"
  "*pipo.cashier.bytedance.net"
  "*player.vimeo.com"
  "*pre-content-os.bytedance.net"
  "*procurement.bytedance.net"
  "*proxima.bytedance.net"
  "*push-api.bytedance.net"
  "*pypi.byted.org"
  "*python.org"
  "*qianxun-os.bytedance.net"
  "*review.byted.org"
  "*rds-sensitive.bytedance.net"
  "*readthedocs.org"
  "*relay.byted.org"
  "*risk-test.bytedance.net"
  "*risk.bytedance.net"
  "*rocket.bytedance.net"
  "*rust-lang.org"
  "*s-hub.byted.org"
  "*sandbox-grafana-appsec.byted.org"
  "*sandbox.bytedance.net"
  "*sandbox.hub.byted.org"
  "*sandboxi18n-grafana-appsec.byted.org"
  "*scm.byted.org"
  "*scm.bytedance.net"
  "*secdata-iboe.bytedance.net"
  "*securepubads.g.doubleclick.net"
  "*security-row.bytedance.net"
  "*security.bytedance.net"
  "*self.cn"
  "*semver.org"
  "*sf16-fe-tos-sg.i18n-pglstatp.com"
  "*sf16-short-va.bytedapm.com"
  "*sg-ei.byted.org"
  "*sg-kaniapis.byted.org"
  "*sg.byted.org"
  "*sg.bytedance.net"
  "*sg1-grafana-appsec.byted.org"
  "*sgee.bytedance.net"
  "*sglark.bytedance.net"
  "*sin-hub.byted.org"
  "*site.bytedance.net"
  "*skyline.bytedance.net"
  "*sourceforge.net"
  "*spaas.admin.cn"
  "*spaas.operator.cn"
  "*spaas.owner.cn"
  "*sre.spaas.cn"
  "*sso-hl.bytedance.com"
  "*sso-tx.bytedance.com"
  "*sso.bytedance.com"
  "*starling-boe-public.bytedance.net"
  "*starling-public.zijieapi.com"
  "*starling.bytedance.net"
  "*starling.pre.bytedance.net"
  "*starling.service.lf.byted.org"
  "*starling.service.va.byted.org"
  "*starling.zijieapi.com"
  "*sugarman.bytedance.net"
  "*sum.golang.google.cn"
  "*sys.bytedance.net"
  "*sysapi.byted.org"
  "*syshub.byted.org"
  "*system.bytedance.net"
  "*sysworkflow.bytedance.net"
  "*tanxiaolin.com"
  "*tcc-ag.byted.org"
  "*tcc-boe.byted.org"
  "*tcc-boe.xfl.net"
  "*tcc-bridge-hl.bytedance.net"
  "*tcc-bridge-lf.bytedance.net"
  "*tcc-bridge-test-hl.bytedance.net"
  "*tcc-bridge-test-lf.bytedance.net"
  "*tcc-bridge-test-lq.bytedance.net"
  "*tcc-bridge.bytedance.net"
  "*tcc-hl.byted.org"
  "*tcc-hl.bytedance.net"
  "*tcc-i18n.byted.org"
  "*tcc-lf.bytedance.net"
  "*tcc-link-i18n.byted.org"
  "*tcc-link-us.byted.org"
  "*tcc-link.byted.org"
  "*tcc-lq.byted.org"
  "*tcc-open-platform-hl.bytedance.net"
  "*tcc-open-platform-lf.bytedance.net"
  "*tcc-open-platform-lq.bytedance.net"
  "*tcc-open-platform.bytedance.net"
  "*tcc-tx.byted.org"
  "*tcc-us.byted.org"
  "*tcc-va-useast2a.byted.org"
  "*tcc.boe.byted.org"
  "*tcc.byted.org"
  "*tcc.operator.cn"
  "*tcc.owner.cn"
  "*tcc.xfl.net"
  "*tce.byted.org"
  "*tcs-bos.bytedance.net"
  "*tcs-sgpre.bytedance.net"
  "*tcs-vapre.bytedance.net"
  "*tcs-web.bytedance.net"
  "*tech.bytedance.net"
  "*test-sso.bytedance.net"
  "*thub.byted.org"
  "*tiktok-news.bytedance.net"
  "*tob-bytedrive-grafana-lq.bytedance.net"
  "*tob-grafana.byted.org"
  "*top.bytedance.net"
  "*tqs.byted.org"
  "*transparency.bytedance.net"
  "*travis-ci.org"
  "*tt-debug.bytedance.net"
  "*twitter.com"
  "*tx-kaniapis.byted.org"
  "*tznavn3x.fn.bytedance.net"
  "*uams-1.bytedance.net"
  "*uams.bytedance.net"
  "*ubuntu.com"
  "*us.bytedance.net"
  "*use-hub.byted.org"
  "*useast-red-hub.byted.org"
  "*useast2a-grafana-appsec.byted.org"
  "*useast2a.bytedance.net"
  "*usw-hub.byted.org"
  "*va-ei.byted.org"
  "*va-grafana-appsec.byted.org"
  "*va-kaniapis.byted.org"
  "*va.byted.org"
  "*vcloud.bytedance.net"
  "*vela.byted.org"
  "*vip-awsfr.bytedance.net"
  "*vpaas-data-engineering.sre-hl.bytedance.net"
  "*vpaas-data-engineering.sre-sgcomm1.bytedance.net"
  "*vpaas-data-engineering.sre.bytedance.net"
  "*vpaas.byted.org"
  "*wiki.bytedance.com"
  "*wiki.bytedance.net"
  "*wikipedia.org"
  "*wp.bytedance.net"
  "*www.alphassl.com"
  "*www.bytedance.com"
  "*www.docker.com"
  "*xuyuqing.com"
  "*yahoo.com"
  "*yanglan.com"
  "*yapi.bytedance.net"
  "*yg-grafana-appsec.byted.org"
  "*youtube.com"
  "*zephyr-test.bytedance.net"
  "*zhanghengwei.com"
  "*ngcc.bytedance.net"
  "*byteflow.bytedance.net"
  "*atum.byted.org"
  "*scm-ttp-us.byted.org"
  "*oncall.bytedance.net"
  "*tao.byted.org"
  "*bits.bytedance.net"
  "*bytecycle.bytedance.net"
  "*sso-va.bytedance.com"
  "*codebase-api.byted.org"
  "*tce-i18n.byted.org"
  "*bytecycle-api.bytedance.net"
  "*cloud-i18n.byted.org"
  "*cloud-us.byted.org"
  "*oncall-backend.bytedance.net"
  "*ad-stats-online-tx-es.byted.org"
  "*tiktokd.org"
  "*npm.byted.org"
  "*fic.byted.org"
  "*eden-lint-v3.web.bytedance.net"
  "*metrics-fe-ttp-us.byted.org"
  "*metrics-fe-i18n.byted.org"
  "*m.tiktok.shop"
  "*api.tiktokglobalshopv.com"
  "stripe.com"
  "https://stripe.com"
  "*.tiktokglobalshop.com"
  "*.ups.com"
  "*.oecstatic.com"
  "*.ttwstatic.com"
  "*.zendesk.com"
  "*.doku.com"
  "feishu.com"
  "https://feishu.com"
  "*.voorbeeld.com"
  "*.esimerkki.com"
  "*.tiktok-us.net"
  "*.tiktokglobalshopv.com"
  "*.intel.com"
  "getbootstrap.com"
  "*.stackexchange.com"
  "*.lark-usts.com"
  "*.tiktokd.net"
  "gerritcodereview.com"
  "www.gerritcodereview.com"
  "www.npmjs.com"
  "*.byteintl.net"
  "*.goofy-cdn.com"
  "*.tiktok-usts.net"
  "*.cdn77.com"
  "*bytesib.bytedance.net"
  "*buildcloudv2.byted.org"
  "*leafboat-ttp-us.byted.org"
  "*bytebuild-ttp-us.byted.org"
  "*bfarm-bazel-ttp.byted.org"
  "*bnpm.byted.org"
  "*luban-source.tiktokd.org"
  "*scm-agent-proxy.tiktokd.org"
  "*atum.tiktokd.org"
  "*image-manager.tiktokd.org"
  "*scm-proxy.tiktokd.org"
  "*scm-tx.tiktokd.org"
  "*objects.githubusercontent.com"
  "*storage.googleapis.com"
  "*developer.download.nvidia.com"
  "*download.docker.com"
  "*nodejs.org"
  "*download.cypress.io"
  "*raw.githubusercontent.com"
  "*downloads.webmproject.org"
  "*downloads.sourceforge.net"
  "*www.lua.org"
  "*www.python.org"
  "*crates.io"
  "*mirror.bazel.build"
  "*packagecloud.io"
  "*dl.google.com"
  "*node-precompiled-binaries.grpc.io"
  "*codeload.github.com"
  "*repo.maven.apache.org"
  "*sh.rustup.rs"
  "*static.rust-lang.org"
  "*download.pytorch.org"
  "*static.crates.io"
  "*ftp.gnu.org"
  "*chrome-infra-packages.appspot.com"
  "*archive.apache.org"
  "*cdn.sheetjs.com"
  "*go.dev"
  "*releases.bazel.build"
  "*bytebuild-nightly.byted.org"
  "*goproxy-sce.byted.org"
  "*sf-unpkg-src.bytedance.net"
  "*gemini.byted.org"
  "*buildboard.byted.org"
)

# ---------------------------------------------------------------------------
# 函数：判断 file_path 是否命中文件白名单
# ---------------------------------------------------------------------------
should_filter_file_path() {
  local file_path="$1"
  local pattern
  [[ -z "$file_path" ]] && return 1
  for pattern in "${DOMAIN_FILTER_FILE_PATH_PATTERNS[@]}"; do
    # shellcheck disable=SC2053
    if [[ "$file_path" == $pattern ]]; then
      return 0
    fi
  done
  return 1
}

# ---------------------------------------------------------------------------
# 函数：判断 domain 是否命中域名白名单
# ---------------------------------------------------------------------------
should_filter_domain() {
  local domain="$1"
  local pattern
  [[ -z "$domain" ]] && return 1
  for pattern in "${DOMAIN_FILTER_DOMAIN_PATTERNS[@]}"; do
    # shellcheck disable=SC2053
    if [[ "$domain" == $pattern ]]; then
      return 0
    fi
  done
  return 1
}

# ---------------------------------------------------------------------------
# 函数：综合判断一条 (file_path, domain) 问题是否应被过滤
#   命中文件白名单 OR 命中域名白名单 → 0（过滤）
# ---------------------------------------------------------------------------
should_filter_domain_issue() {
  local file_path="$1"
  local domain="$2"
  if should_filter_file_path "$file_path"; then
    return 0
  fi
  if should_filter_domain "$domain"; then
    return 0
  fi
  return 1
}

# ---------------------------------------------------------------------------
# 独立 CLI 模式：仅在脚本被直接执行（非 source）时生效
# 输入：每行 TAB 分隔，第 1 列 file_path，第 2 列 domain，第 3+ 列为附加上下文
# 输出：未命中白名单的行原样输出
# ---------------------------------------------------------------------------
if [[ "${BASH_SOURCE[0]}" == "$0" ]]; then
  while IFS=$'\t' read -r file_path domain rest || [[ -n "$file_path$domain$rest" ]]; do
    [[ -z "$file_path" && -z "$domain" ]] && continue
    if should_filter_domain_issue "$file_path" "$domain"; then
      continue
    fi
    if [[ -n "$rest" ]]; then
      printf '%s\t%s\t%s\n' "$file_path" "$domain" "$rest"
    else
      printf '%s\t%s\n' "$file_path" "$domain"
    fi
  done
fi
